public class WebServiceCallout {
    private final static String authToken = '<Your API KEY HERE>';
	private final static String sEndPoint = '<Callout: DefaultEndpointsProtocol=https;AccountName=storageaccountsourcb5c6;AccountKey=5qoll6hdey5anLLpGLvCLGjT/KwqrJj9JmM6p9yISE5MJ/M7ZKM6XQVp+RhSJDOZ0i/AoWeIdWcTQnYX1+fg/Q==;EndpointSuffix=core.windows.net';
    private final static Integer iTimeout = 20000;
}